// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-35RxbOCE8ku0sH_fILVu-KygYtYIDI',
    appId: '1:149640112489:web:3e29959f9b512d894575f8',
    messagingSenderId: '149640112489',
    projectId: 'avid-involution-373812',
    authDomain: 'avid-involution-373812.firebaseapp.com',
    storageBucket: 'avid-involution-373812.appspot.com',
    measurementId: 'G-MB8QZQLVY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT75k7A7Lps8U-gRc9an7VriYWwMXU2kM',
    appId: '1:149640112489:android:9256f38d3dc2e9274575f8',
    messagingSenderId: '149640112489',
    projectId: 'avid-involution-373812',
    storageBucket: 'avid-involution-373812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBe_WUx52yArRONKF8SiO6bI2ZgEywUg',
    appId: '1:149640112489:ios:ebd4a7ec80b6aeb84575f8',
    messagingSenderId: '149640112489',
    projectId: 'avid-involution-373812',
    storageBucket: 'avid-involution-373812.appspot.com',
    iosBundleId: 'com.example.bridgebankSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBe_WUx52yArRONKF8SiO6bI2ZgEywUg',
    appId: '1:149640112489:ios:ebd4a7ec80b6aeb84575f8',
    messagingSenderId: '149640112489',
    projectId: 'avid-involution-373812',
    storageBucket: 'avid-involution-373812.appspot.com',
    iosBundleId: 'com.example.bridgebankSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF-35RxbOCE8ku0sH_fILVu-KygYtYIDI',
    appId: '1:149640112489:web:f4aa7939964f751d4575f8',
    messagingSenderId: '149640112489',
    projectId: 'avid-involution-373812',
    authDomain: 'avid-involution-373812.firebaseapp.com',
    storageBucket: 'avid-involution-373812.appspot.com',
    measurementId: 'G-F95248CN1M',
  );
}
